name: mytree-server

services:
  mytree-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    volumes:
      - .:/home/node/app
      - ./dist:/home/node/app/dist
    depends_on:
      - pg
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mytree